//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("sp_studentModel", "FK__tbl_stude__S_Cla__145C0A3F", "tbl_class", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(sp_dal.tbl_class), "tbl_student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(sp_dal.tbl_student), true)]
[assembly: EdmRelationshipAttribute("sp_studentModel", "FK__tbl_stu_m__cou_n__1273C1CD", "tbl_course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(sp_dal.tbl_course), "tbl_stu_mark", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(sp_dal.tbl_stu_mark), true)]
[assembly: EdmRelationshipAttribute("sp_studentModel", "FK__tbl_stu_m__stu_n__1367E606", "tbl_student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(sp_dal.tbl_student), "tbl_stu_mark", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(sp_dal.tbl_stu_mark), true)]

#endregion

namespace sp_dal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataBase : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataBase object using the connection string found in the 'DataBase' section of the application configuration file.
        /// </summary>
        public DataBase() : base("name=DataBase", "DataBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataBase object.
        /// </summary>
        public DataBase(string connectionString) : base(connectionString, "DataBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataBase object.
        /// </summary>
        public DataBase(EntityConnection connection) : base(connection, "DataBase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_class> tbl_class
        {
            get
            {
                if ((_tbl_class == null))
                {
                    _tbl_class = base.CreateObjectSet<tbl_class>("tbl_class");
                }
                return _tbl_class;
            }
        }
        private ObjectSet<tbl_class> _tbl_class;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_course> tbl_course
        {
            get
            {
                if ((_tbl_course == null))
                {
                    _tbl_course = base.CreateObjectSet<tbl_course>("tbl_course");
                }
                return _tbl_course;
            }
        }
        private ObjectSet<tbl_course> _tbl_course;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_stu_mark> tbl_stu_mark
        {
            get
            {
                if ((_tbl_stu_mark == null))
                {
                    _tbl_stu_mark = base.CreateObjectSet<tbl_stu_mark>("tbl_stu_mark");
                }
                return _tbl_stu_mark;
            }
        }
        private ObjectSet<tbl_stu_mark> _tbl_stu_mark;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_student> tbl_student
        {
            get
            {
                if ((_tbl_student == null))
                {
                    _tbl_student = base.CreateObjectSet<tbl_student>("tbl_student");
                }
                return _tbl_student;
            }
        }
        private ObjectSet<tbl_student> _tbl_student;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_user> tbl_user
        {
            get
            {
                if ((_tbl_user == null))
                {
                    _tbl_user = base.CreateObjectSet<tbl_user>("tbl_user");
                }
                return _tbl_user;
            }
        }
        private ObjectSet<tbl_user> _tbl_user;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_mark> v_mark
        {
            get
            {
                if ((_v_mark == null))
                {
                    _v_mark = base.CreateObjectSet<v_mark>("v_mark");
                }
                return _v_mark;
            }
        }
        private ObjectSet<v_mark> _v_mark;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_class EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_class(tbl_class tbl_class)
        {
            base.AddObject("tbl_class", tbl_class);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_course EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_course(tbl_course tbl_course)
        {
            base.AddObject("tbl_course", tbl_course);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_stu_mark EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_stu_mark(tbl_stu_mark tbl_stu_mark)
        {
            base.AddObject("tbl_stu_mark", tbl_stu_mark);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_student EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_student(tbl_student tbl_student)
        {
            base.AddObject("tbl_student", tbl_student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_user(tbl_user tbl_user)
        {
            base.AddObject("tbl_user", tbl_user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_mark EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_mark(v_mark v_mark)
        {
            base.AddObject("v_mark", v_mark);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sp_studentModel", Name="tbl_class")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_class : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_class object.
        /// </summary>
        /// <param name="cl_index">Initial value of the cl_index property.</param>
        /// <param name="cl_ID">Initial value of the cl_ID property.</param>
        /// <param name="cl_Name">Initial value of the cl_Name property.</param>
        public static tbl_class Createtbl_class(global::System.Int32 cl_index, global::System.String cl_ID, global::System.String cl_Name)
        {
            tbl_class tbl_class = new tbl_class();
            tbl_class.cl_index = cl_index;
            tbl_class.cl_ID = cl_ID;
            tbl_class.cl_Name = cl_Name;
            return tbl_class;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cl_index
        {
            get
            {
                return _cl_index;
            }
            set
            {
                Oncl_indexChanging(value);
                ReportPropertyChanging("cl_index");
                _cl_index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cl_index");
                Oncl_indexChanged();
            }
        }
        private global::System.Int32 _cl_index;
        partial void Oncl_indexChanging(global::System.Int32 value);
        partial void Oncl_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cl_ID
        {
            get
            {
                return _cl_ID;
            }
            set
            {
                if (_cl_ID != value)
                {
                    Oncl_IDChanging(value);
                    ReportPropertyChanging("cl_ID");
                    _cl_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cl_ID");
                    Oncl_IDChanged();
                }
            }
        }
        private global::System.String _cl_ID;
        partial void Oncl_IDChanging(global::System.String value);
        partial void Oncl_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cl_Name
        {
            get
            {
                return _cl_Name;
            }
            set
            {
                Oncl_NameChanging(value);
                ReportPropertyChanging("cl_Name");
                _cl_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cl_Name");
                Oncl_NameChanged();
            }
        }
        private global::System.String _cl_Name;
        partial void Oncl_NameChanging(global::System.String value);
        partial void Oncl_NameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sp_studentModel", "FK__tbl_stude__S_Cla__145C0A3F", "tbl_student")]
        public EntityCollection<tbl_student> tbl_student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_student>("sp_studentModel.FK__tbl_stude__S_Cla__145C0A3F", "tbl_student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_student>("sp_studentModel.FK__tbl_stude__S_Cla__145C0A3F", "tbl_student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sp_studentModel", Name="tbl_course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_course object.
        /// </summary>
        /// <param name="c_index">Initial value of the C_index property.</param>
        /// <param name="c_Num">Initial value of the C_Num property.</param>
        /// <param name="c_Name">Initial value of the C_Name property.</param>
        public static tbl_course Createtbl_course(global::System.Int32 c_index, global::System.String c_Num, global::System.String c_Name)
        {
            tbl_course tbl_course = new tbl_course();
            tbl_course.C_index = c_index;
            tbl_course.C_Num = c_Num;
            tbl_course.C_Name = c_Name;
            return tbl_course;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_index
        {
            get
            {
                return _C_index;
            }
            set
            {
                OnC_indexChanging(value);
                ReportPropertyChanging("C_index");
                _C_index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_index");
                OnC_indexChanged();
            }
        }
        private global::System.Int32 _C_index;
        partial void OnC_indexChanging(global::System.Int32 value);
        partial void OnC_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_Num
        {
            get
            {
                return _C_Num;
            }
            set
            {
                if (_C_Num != value)
                {
                    OnC_NumChanging(value);
                    ReportPropertyChanging("C_Num");
                    _C_Num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("C_Num");
                    OnC_NumChanged();
                }
            }
        }
        private global::System.String _C_Num;
        partial void OnC_NumChanging(global::System.String value);
        partial void OnC_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_Name
        {
            get
            {
                return _C_Name;
            }
            set
            {
                OnC_NameChanging(value);
                ReportPropertyChanging("C_Name");
                _C_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("C_Name");
                OnC_NameChanged();
            }
        }
        private global::System.String _C_Name;
        partial void OnC_NameChanging(global::System.String value);
        partial void OnC_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_Course
        {
            get
            {
                return _C_Course;
            }
            set
            {
                OnC_CourseChanging(value);
                ReportPropertyChanging("C_Course");
                _C_Course = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_Course");
                OnC_CourseChanged();
            }
        }
        private global::System.String _C_Course;
        partial void OnC_CourseChanging(global::System.String value);
        partial void OnC_CourseChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sp_studentModel", "FK__tbl_stu_m__cou_n__1273C1CD", "tbl_stu_mark")]
        public EntityCollection<tbl_stu_mark> tbl_stu_mark
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_stu_mark>("sp_studentModel.FK__tbl_stu_m__cou_n__1273C1CD", "tbl_stu_mark");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_stu_mark>("sp_studentModel.FK__tbl_stu_m__cou_n__1273C1CD", "tbl_stu_mark", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sp_studentModel", Name="tbl_stu_mark")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_stu_mark : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_stu_mark object.
        /// </summary>
        /// <param name="mk_index">Initial value of the mk_index property.</param>
        /// <param name="stu_num">Initial value of the stu_num property.</param>
        /// <param name="cou_num">Initial value of the cou_num property.</param>
        /// <param name="mk_mark">Initial value of the mk_mark property.</param>
        public static tbl_stu_mark Createtbl_stu_mark(global::System.Int32 mk_index, global::System.String stu_num, global::System.String cou_num, global::System.Decimal mk_mark)
        {
            tbl_stu_mark tbl_stu_mark = new tbl_stu_mark();
            tbl_stu_mark.mk_index = mk_index;
            tbl_stu_mark.stu_num = stu_num;
            tbl_stu_mark.cou_num = cou_num;
            tbl_stu_mark.mk_mark = mk_mark;
            return tbl_stu_mark;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mk_index
        {
            get
            {
                return _mk_index;
            }
            set
            {
                Onmk_indexChanging(value);
                ReportPropertyChanging("mk_index");
                _mk_index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mk_index");
                Onmk_indexChanged();
            }
        }
        private global::System.Int32 _mk_index;
        partial void Onmk_indexChanging(global::System.Int32 value);
        partial void Onmk_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String stu_num
        {
            get
            {
                return _stu_num;
            }
            set
            {
                if (_stu_num != value)
                {
                    Onstu_numChanging(value);
                    ReportPropertyChanging("stu_num");
                    _stu_num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("stu_num");
                    Onstu_numChanged();
                }
            }
        }
        private global::System.String _stu_num;
        partial void Onstu_numChanging(global::System.String value);
        partial void Onstu_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cou_num
        {
            get
            {
                return _cou_num;
            }
            set
            {
                if (_cou_num != value)
                {
                    Oncou_numChanging(value);
                    ReportPropertyChanging("cou_num");
                    _cou_num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cou_num");
                    Oncou_numChanged();
                }
            }
        }
        private global::System.String _cou_num;
        partial void Oncou_numChanging(global::System.String value);
        partial void Oncou_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal mk_mark
        {
            get
            {
                return _mk_mark;
            }
            set
            {
                Onmk_markChanging(value);
                ReportPropertyChanging("mk_mark");
                _mk_mark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mk_mark");
                Onmk_markChanged();
            }
        }
        private global::System.Decimal _mk_mark;
        partial void Onmk_markChanging(global::System.Decimal value);
        partial void Onmk_markChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sp_studentModel", "FK__tbl_stu_m__cou_n__1273C1CD", "tbl_course")]
        public tbl_course tbl_course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_course>("sp_studentModel.FK__tbl_stu_m__cou_n__1273C1CD", "tbl_course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_course>("sp_studentModel.FK__tbl_stu_m__cou_n__1273C1CD", "tbl_course").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_course> tbl_courseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_course>("sp_studentModel.FK__tbl_stu_m__cou_n__1273C1CD", "tbl_course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_course>("sp_studentModel.FK__tbl_stu_m__cou_n__1273C1CD", "tbl_course", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sp_studentModel", "FK__tbl_stu_m__stu_n__1367E606", "tbl_student")]
        public tbl_student tbl_student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("sp_studentModel.FK__tbl_stu_m__stu_n__1367E606", "tbl_student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("sp_studentModel.FK__tbl_stu_m__stu_n__1367E606", "tbl_student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_student> tbl_studentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("sp_studentModel.FK__tbl_stu_m__stu_n__1367E606", "tbl_student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_student>("sp_studentModel.FK__tbl_stu_m__stu_n__1367E606", "tbl_student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sp_studentModel", Name="tbl_student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_student object.
        /// </summary>
        /// <param name="s_index">Initial value of the S_index property.</param>
        /// <param name="s_Num">Initial value of the S_Num property.</param>
        /// <param name="s_Name">Initial value of the S_Name property.</param>
        /// <param name="s_Gender">Initial value of the S_Gender property.</param>
        /// <param name="s_Birthday">Initial value of the S_Birthday property.</param>
        /// <param name="s_ClassID">Initial value of the S_ClassID property.</param>
        public static tbl_student Createtbl_student(global::System.Int32 s_index, global::System.String s_Num, global::System.String s_Name, global::System.String s_Gender, global::System.DateTime s_Birthday, global::System.String s_ClassID)
        {
            tbl_student tbl_student = new tbl_student();
            tbl_student.S_index = s_index;
            tbl_student.S_Num = s_Num;
            tbl_student.S_Name = s_Name;
            tbl_student.S_Gender = s_Gender;
            tbl_student.S_Birthday = s_Birthday;
            tbl_student.S_ClassID = s_ClassID;
            return tbl_student;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 S_index
        {
            get
            {
                return _S_index;
            }
            set
            {
                OnS_indexChanging(value);
                ReportPropertyChanging("S_index");
                _S_index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("S_index");
                OnS_indexChanged();
            }
        }
        private global::System.Int32 _S_index;
        partial void OnS_indexChanging(global::System.Int32 value);
        partial void OnS_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_Num
        {
            get
            {
                return _S_Num;
            }
            set
            {
                if (_S_Num != value)
                {
                    OnS_NumChanging(value);
                    ReportPropertyChanging("S_Num");
                    _S_Num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("S_Num");
                    OnS_NumChanged();
                }
            }
        }
        private global::System.String _S_Num;
        partial void OnS_NumChanging(global::System.String value);
        partial void OnS_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_Name
        {
            get
            {
                return _S_Name;
            }
            set
            {
                OnS_NameChanging(value);
                ReportPropertyChanging("S_Name");
                _S_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("S_Name");
                OnS_NameChanged();
            }
        }
        private global::System.String _S_Name;
        partial void OnS_NameChanging(global::System.String value);
        partial void OnS_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_Gender
        {
            get
            {
                return _S_Gender;
            }
            set
            {
                OnS_GenderChanging(value);
                ReportPropertyChanging("S_Gender");
                _S_Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("S_Gender");
                OnS_GenderChanged();
            }
        }
        private global::System.String _S_Gender;
        partial void OnS_GenderChanging(global::System.String value);
        partial void OnS_GenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime S_Birthday
        {
            get
            {
                return _S_Birthday;
            }
            set
            {
                OnS_BirthdayChanging(value);
                ReportPropertyChanging("S_Birthday");
                _S_Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("S_Birthday");
                OnS_BirthdayChanged();
            }
        }
        private global::System.DateTime _S_Birthday;
        partial void OnS_BirthdayChanging(global::System.DateTime value);
        partial void OnS_BirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String S_Department
        {
            get
            {
                return _S_Department;
            }
            set
            {
                OnS_DepartmentChanging(value);
                ReportPropertyChanging("S_Department");
                _S_Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("S_Department");
                OnS_DepartmentChanged();
            }
        }
        private global::System.String _S_Department;
        partial void OnS_DepartmentChanging(global::System.String value);
        partial void OnS_DepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_ClassID
        {
            get
            {
                return _S_ClassID;
            }
            set
            {
                OnS_ClassIDChanging(value);
                ReportPropertyChanging("S_ClassID");
                _S_ClassID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("S_ClassID");
                OnS_ClassIDChanged();
            }
        }
        private global::System.String _S_ClassID;
        partial void OnS_ClassIDChanging(global::System.String value);
        partial void OnS_ClassIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sp_studentModel", "FK__tbl_stude__S_Cla__145C0A3F", "tbl_class")]
        public tbl_class tbl_class
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_class>("sp_studentModel.FK__tbl_stude__S_Cla__145C0A3F", "tbl_class").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_class>("sp_studentModel.FK__tbl_stude__S_Cla__145C0A3F", "tbl_class").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_class> tbl_classReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_class>("sp_studentModel.FK__tbl_stude__S_Cla__145C0A3F", "tbl_class");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_class>("sp_studentModel.FK__tbl_stude__S_Cla__145C0A3F", "tbl_class", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sp_studentModel", "FK__tbl_stu_m__stu_n__1367E606", "tbl_stu_mark")]
        public EntityCollection<tbl_stu_mark> tbl_stu_mark
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_stu_mark>("sp_studentModel.FK__tbl_stu_m__stu_n__1367E606", "tbl_stu_mark");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_stu_mark>("sp_studentModel.FK__tbl_stu_m__stu_n__1367E606", "tbl_stu_mark", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sp_studentModel", Name="tbl_user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_user object.
        /// </summary>
        /// <param name="u_index">Initial value of the U_index property.</param>
        /// <param name="u_ID">Initial value of the U_ID property.</param>
        /// <param name="u_PWD">Initial value of the U_PWD property.</param>
        /// <param name="u_Power">Initial value of the U_Power property.</param>
        public static tbl_user Createtbl_user(global::System.Int32 u_index, global::System.String u_ID, global::System.String u_PWD, global::System.Int32 u_Power)
        {
            tbl_user tbl_user = new tbl_user();
            tbl_user.U_index = u_index;
            tbl_user.U_ID = u_ID;
            tbl_user.U_PWD = u_PWD;
            tbl_user.U_Power = u_Power;
            return tbl_user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 U_index
        {
            get
            {
                return _U_index;
            }
            set
            {
                OnU_indexChanging(value);
                ReportPropertyChanging("U_index");
                _U_index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_index");
                OnU_indexChanged();
            }
        }
        private global::System.Int32 _U_index;
        partial void OnU_indexChanging(global::System.Int32 value);
        partial void OnU_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_ID
        {
            get
            {
                return _U_ID;
            }
            set
            {
                if (_U_ID != value)
                {
                    OnU_IDChanging(value);
                    ReportPropertyChanging("U_ID");
                    _U_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("U_ID");
                    OnU_IDChanged();
                }
            }
        }
        private global::System.String _U_ID;
        partial void OnU_IDChanging(global::System.String value);
        partial void OnU_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String U_PWD
        {
            get
            {
                return _U_PWD;
            }
            set
            {
                OnU_PWDChanging(value);
                ReportPropertyChanging("U_PWD");
                _U_PWD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("U_PWD");
                OnU_PWDChanged();
            }
        }
        private global::System.String _U_PWD;
        partial void OnU_PWDChanging(global::System.String value);
        partial void OnU_PWDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 U_Power
        {
            get
            {
                return _U_Power;
            }
            set
            {
                OnU_PowerChanging(value);
                ReportPropertyChanging("U_Power");
                _U_Power = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_Power");
                OnU_PowerChanged();
            }
        }
        private global::System.Int32 _U_Power;
        partial void OnU_PowerChanging(global::System.Int32 value);
        partial void OnU_PowerChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sp_studentModel", Name="v_mark")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_mark : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_mark object.
        /// </summary>
        /// <param name="mk_index">Initial value of the mk_index property.</param>
        /// <param name="stu_num">Initial value of the stu_num property.</param>
        /// <param name="cou_num">Initial value of the cou_num property.</param>
        /// <param name="mk_mark">Initial value of the mk_mark property.</param>
        /// <param name="s_index">Initial value of the S_index property.</param>
        /// <param name="s_Num">Initial value of the S_Num property.</param>
        /// <param name="s_Name">Initial value of the S_Name property.</param>
        /// <param name="s_Gender">Initial value of the S_Gender property.</param>
        /// <param name="s_Birthday">Initial value of the S_Birthday property.</param>
        /// <param name="s_ClassID">Initial value of the S_ClassID property.</param>
        /// <param name="c_index">Initial value of the C_index property.</param>
        /// <param name="c_Num">Initial value of the C_Num property.</param>
        /// <param name="c_Name">Initial value of the C_Name property.</param>
        /// <param name="cl_index">Initial value of the cl_index property.</param>
        /// <param name="cl_ID">Initial value of the cl_ID property.</param>
        /// <param name="cl_Name">Initial value of the cl_Name property.</param>
        public static v_mark Createv_mark(global::System.Int32 mk_index, global::System.String stu_num, global::System.String cou_num, global::System.Decimal mk_mark, global::System.Int32 s_index, global::System.String s_Num, global::System.String s_Name, global::System.String s_Gender, global::System.DateTime s_Birthday, global::System.String s_ClassID, global::System.Int32 c_index, global::System.String c_Num, global::System.String c_Name, global::System.Int32 cl_index, global::System.String cl_ID, global::System.String cl_Name)
        {
            v_mark v_mark = new v_mark();
            v_mark.mk_index = mk_index;
            v_mark.stu_num = stu_num;
            v_mark.cou_num = cou_num;
            v_mark.mk_mark = mk_mark;
            v_mark.S_index = s_index;
            v_mark.S_Num = s_Num;
            v_mark.S_Name = s_Name;
            v_mark.S_Gender = s_Gender;
            v_mark.S_Birthday = s_Birthday;
            v_mark.S_ClassID = s_ClassID;
            v_mark.C_index = c_index;
            v_mark.C_Num = c_Num;
            v_mark.C_Name = c_Name;
            v_mark.cl_index = cl_index;
            v_mark.cl_ID = cl_ID;
            v_mark.cl_Name = cl_Name;
            return v_mark;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mk_index
        {
            get
            {
                return _mk_index;
            }
            set
            {
                if (_mk_index != value)
                {
                    Onmk_indexChanging(value);
                    ReportPropertyChanging("mk_index");
                    _mk_index = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mk_index");
                    Onmk_indexChanged();
                }
            }
        }
        private global::System.Int32 _mk_index;
        partial void Onmk_indexChanging(global::System.Int32 value);
        partial void Onmk_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String stu_num
        {
            get
            {
                return _stu_num;
            }
            set
            {
                if (_stu_num != value)
                {
                    Onstu_numChanging(value);
                    ReportPropertyChanging("stu_num");
                    _stu_num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("stu_num");
                    Onstu_numChanged();
                }
            }
        }
        private global::System.String _stu_num;
        partial void Onstu_numChanging(global::System.String value);
        partial void Onstu_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cou_num
        {
            get
            {
                return _cou_num;
            }
            set
            {
                if (_cou_num != value)
                {
                    Oncou_numChanging(value);
                    ReportPropertyChanging("cou_num");
                    _cou_num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cou_num");
                    Oncou_numChanged();
                }
            }
        }
        private global::System.String _cou_num;
        partial void Oncou_numChanging(global::System.String value);
        partial void Oncou_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal mk_mark
        {
            get
            {
                return _mk_mark;
            }
            set
            {
                if (_mk_mark != value)
                {
                    Onmk_markChanging(value);
                    ReportPropertyChanging("mk_mark");
                    _mk_mark = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mk_mark");
                    Onmk_markChanged();
                }
            }
        }
        private global::System.Decimal _mk_mark;
        partial void Onmk_markChanging(global::System.Decimal value);
        partial void Onmk_markChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 S_index
        {
            get
            {
                return _S_index;
            }
            set
            {
                if (_S_index != value)
                {
                    OnS_indexChanging(value);
                    ReportPropertyChanging("S_index");
                    _S_index = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("S_index");
                    OnS_indexChanged();
                }
            }
        }
        private global::System.Int32 _S_index;
        partial void OnS_indexChanging(global::System.Int32 value);
        partial void OnS_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_Num
        {
            get
            {
                return _S_Num;
            }
            set
            {
                if (_S_Num != value)
                {
                    OnS_NumChanging(value);
                    ReportPropertyChanging("S_Num");
                    _S_Num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("S_Num");
                    OnS_NumChanged();
                }
            }
        }
        private global::System.String _S_Num;
        partial void OnS_NumChanging(global::System.String value);
        partial void OnS_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_Name
        {
            get
            {
                return _S_Name;
            }
            set
            {
                if (_S_Name != value)
                {
                    OnS_NameChanging(value);
                    ReportPropertyChanging("S_Name");
                    _S_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("S_Name");
                    OnS_NameChanged();
                }
            }
        }
        private global::System.String _S_Name;
        partial void OnS_NameChanging(global::System.String value);
        partial void OnS_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_Gender
        {
            get
            {
                return _S_Gender;
            }
            set
            {
                if (_S_Gender != value)
                {
                    OnS_GenderChanging(value);
                    ReportPropertyChanging("S_Gender");
                    _S_Gender = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("S_Gender");
                    OnS_GenderChanged();
                }
            }
        }
        private global::System.String _S_Gender;
        partial void OnS_GenderChanging(global::System.String value);
        partial void OnS_GenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime S_Birthday
        {
            get
            {
                return _S_Birthday;
            }
            set
            {
                if (_S_Birthday != value)
                {
                    OnS_BirthdayChanging(value);
                    ReportPropertyChanging("S_Birthday");
                    _S_Birthday = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("S_Birthday");
                    OnS_BirthdayChanged();
                }
            }
        }
        private global::System.DateTime _S_Birthday;
        partial void OnS_BirthdayChanging(global::System.DateTime value);
        partial void OnS_BirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String S_Department
        {
            get
            {
                return _S_Department;
            }
            set
            {
                OnS_DepartmentChanging(value);
                ReportPropertyChanging("S_Department");
                _S_Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("S_Department");
                OnS_DepartmentChanged();
            }
        }
        private global::System.String _S_Department;
        partial void OnS_DepartmentChanging(global::System.String value);
        partial void OnS_DepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String S_ClassID
        {
            get
            {
                return _S_ClassID;
            }
            set
            {
                if (_S_ClassID != value)
                {
                    OnS_ClassIDChanging(value);
                    ReportPropertyChanging("S_ClassID");
                    _S_ClassID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("S_ClassID");
                    OnS_ClassIDChanged();
                }
            }
        }
        private global::System.String _S_ClassID;
        partial void OnS_ClassIDChanging(global::System.String value);
        partial void OnS_ClassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_index
        {
            get
            {
                return _C_index;
            }
            set
            {
                if (_C_index != value)
                {
                    OnC_indexChanging(value);
                    ReportPropertyChanging("C_index");
                    _C_index = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("C_index");
                    OnC_indexChanged();
                }
            }
        }
        private global::System.Int32 _C_index;
        partial void OnC_indexChanging(global::System.Int32 value);
        partial void OnC_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_Num
        {
            get
            {
                return _C_Num;
            }
            set
            {
                if (_C_Num != value)
                {
                    OnC_NumChanging(value);
                    ReportPropertyChanging("C_Num");
                    _C_Num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("C_Num");
                    OnC_NumChanged();
                }
            }
        }
        private global::System.String _C_Num;
        partial void OnC_NumChanging(global::System.String value);
        partial void OnC_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_Name
        {
            get
            {
                return _C_Name;
            }
            set
            {
                if (_C_Name != value)
                {
                    OnC_NameChanging(value);
                    ReportPropertyChanging("C_Name");
                    _C_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("C_Name");
                    OnC_NameChanged();
                }
            }
        }
        private global::System.String _C_Name;
        partial void OnC_NameChanging(global::System.String value);
        partial void OnC_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_Course
        {
            get
            {
                return _C_Course;
            }
            set
            {
                OnC_CourseChanging(value);
                ReportPropertyChanging("C_Course");
                _C_Course = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_Course");
                OnC_CourseChanged();
            }
        }
        private global::System.String _C_Course;
        partial void OnC_CourseChanging(global::System.String value);
        partial void OnC_CourseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cl_index
        {
            get
            {
                return _cl_index;
            }
            set
            {
                if (_cl_index != value)
                {
                    Oncl_indexChanging(value);
                    ReportPropertyChanging("cl_index");
                    _cl_index = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cl_index");
                    Oncl_indexChanged();
                }
            }
        }
        private global::System.Int32 _cl_index;
        partial void Oncl_indexChanging(global::System.Int32 value);
        partial void Oncl_indexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cl_ID
        {
            get
            {
                return _cl_ID;
            }
            set
            {
                if (_cl_ID != value)
                {
                    Oncl_IDChanging(value);
                    ReportPropertyChanging("cl_ID");
                    _cl_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cl_ID");
                    Oncl_IDChanged();
                }
            }
        }
        private global::System.String _cl_ID;
        partial void Oncl_IDChanging(global::System.String value);
        partial void Oncl_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cl_Name
        {
            get
            {
                return _cl_Name;
            }
            set
            {
                if (_cl_Name != value)
                {
                    Oncl_NameChanging(value);
                    ReportPropertyChanging("cl_Name");
                    _cl_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("cl_Name");
                    Oncl_NameChanged();
                }
            }
        }
        private global::System.String _cl_Name;
        partial void Oncl_NameChanging(global::System.String value);
        partial void Oncl_NameChanged();

        #endregion

    
    }

    #endregion

    
}
